### ISSUE TITLE
Input files with "." in the name are not properly detected

### ISSUE THREAD

**Issue by cappscolton** [mateuszdrwal/kattis-tools#5]
Some kattis problems have input files like "carrots.01.in" (https://open.kattis.com/problems/carrots)
The command: 'python kattis-tools.py judge' doesn't properly detect such files
Quick fix:
change line 211 to:
        if file.endswith(".in") and ("%s.ans" % ".".join(file.split(".")[:-1]) in files or args.validator):

**Comment by mateuszdrwal** [comment]
Fixed in ba5ac7c, thanks.
